# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRtqYi_SmDQbfo348QMzCjF5e1PDgfr6
"""

import pandas as pd
df = pd.DataFrame({ 'ism' : ['Dilshod', 'Abdullo', 'Ilhom', 'Abdulbosit', 'Muhammadjon', 'Zikrullo', 'Temur','Muhammadjon','Xusniddin','Jaloliddin'],
                  ' Familiya' : [ 'Mamatvaliyev', 'Muhammadaliyev', 'Eshboyev', 'Turgunov', 'Sobirov', 'Mamadaliyev', 'Yusubov','Doltaboyev', 'Yoldashev','Mirzahmedov'],
                    '   yoshi' : ['19','19','19','19','19','19','19','19','19','19'],
                       '  kursi' : ['2','2','2','2','2','2','2','2','2','2' ]

})
print(df)

df.to_excel('malumot.xlsx' ,  index=False, sheet_name='Sheet1')